package com.dnd.doughndrink.models;
// Generated Mar 3, 2023, 7:32:16 PM by Hibernate Tools 6.0.0.Alpha2


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
 
import static jakarta.persistence.GenerationType.IDENTITY;
  
import jakarta.persistence.*; 

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,catalog="doughndrink"
)
public class Orders  implements java.io.Serializable {


     private Integer orderId;
     private User user;
     private String paymentType;
     private Date shippingDate;
     private Date orderDate;
     private Double totaPrice;
     private Set<OrderContainsProduct> orderContainsProducts = new HashSet<OrderContainsProduct>(0);

    public Orders() {
    }

	
    public Orders(Date shippingDate, Date orderDate) {
        this.shippingDate = shippingDate;
        this.orderDate = orderDate;
    }
    public Orders(User user, String paymentType, Date shippingDate, Date orderDate, Set<OrderContainsProduct> orderContainsProducts) {
       this.user = user;
       this.paymentType = paymentType;
       this.shippingDate = shippingDate;
       this.orderDate = orderDate;
       this.orderContainsProducts = orderContainsProducts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="order_id", unique=true, nullable=false)
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="payment_type", length=10)
    public String getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="shipping_date", nullable=false, length=19)
    public Date getShippingDate() {
        return this.shippingDate;
    }
    
    public void setShippingDate(Date shippingDate) {
        this.shippingDate = shippingDate;
    }

    @Column(name="total_price", nullable=false, length=19)
    public Double getTotaPrice() {
        return this.totaPrice;
    }
    
    public void setTotaPrice(Double totaPrice) {
        this.totaPrice = totaPrice;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="order_date", nullable=false, length=19)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set<OrderContainsProduct> getOrderContainsProducts() {
        return this.orderContainsProducts;
    }
    
    public void setOrderContainsProducts(Set<OrderContainsProduct> orderContainsProducts) {
        this.orderContainsProducts = orderContainsProducts;
    }




}


