package com.ecommerce.models;
// Generated Mar 3, 2023, 7:32:16 PM by Hibernate Tools 6.0.0.Alpha2


import java.util.HashSet;
import java.util.Set;  
import jakarta.persistence.*; 

import static jakarta.persistence.GenerationType.IDENTITY; 

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="doughndrink"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Category  implements java.io.Serializable {


     private Integer categoryId;
     private String name;
     private Set<SubCategory> subCategories = new HashSet<SubCategory>(0);

    public Category() {
    }

	
    public Category(String name) {
        this.name = name;
    }
    public Category(String name, Set<SubCategory> subCategories) {
       this.name = name;
       this.subCategories = subCategories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="category_id", unique=true, nullable=false)
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="name", unique=true, nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<SubCategory> getSubCategories() {
        return this.subCategories;
    }
    
    public void setSubCategories(Set<SubCategory> subCategories) {
        this.subCategories = subCategories;
    }




}


